### ISSUE TITLE
Hardcoded Webhook

### ISSUE THREAD

**Issue by freakexeuLow** [sbpp/discord-forward#11]
>
> 
> `and how does the system recognize the sourcebans of the ban and report them in the discord`
> 
> It uses the forwards. If I understand the question correctly.
> 
> Also, you should really be opening your own issue instead of hitchhiking another one that does not hardcode the value.

Done and I should open my own contribution^^ And the plugin reported bans to the Discord. So the question was how the system recognizes it if you don't have to enter the URL of the banlist. And according to the debug message, the plugin should work now because there are no errors in the logs. I use now TheByKotik (sbpp_discord_debug.sp) plugin, she or he added a few changes.
[sbpp_discord_debug.zip](https://github.com/sbpp/discord-forward/files/4049748/sbpp_discord_debug.zip)

**Comment by TheByKotik** [comment]
> > `and how does the system recognize the sourcebans of the ban and report them in the discord`
> > It uses the forwards. If I understand the question correctly.
> > Also, you should really be opening your own issue instead of hitchhiking another one that does not hardcode the value.
> 
> Done and I should open my own contribution^^ And the plugin reported bans to the Discord. So the question was how the system recognizes it if you don't have to enter the URL of the banlist. And according to the debug message, the plugin should work now because there are no errors in the logs. I use now TheByKotik (sbpp_discord_debug.sp) plugin, she or he added a few changes.
> [sbpp_discord_debug.zip](https://github.com/sbpp/discord-forward/files/4049748/sbpp_discord_debug.zip)

Now try send report and ban and mute yourself for a minute.
In log you must see `SendReport() Ban:` and etc.
If webhooks are correct but `Missing ban hook endpoints`, it's be very strange.

**Comment by freakexeuLow** [comment]
> 
> 
> > > `and how does the system recognize the sourcebans of the ban and report them in the discord`
> > > It uses the forwards. If I understand the question correctly.
> > > Also, you should really be opening your own issue instead of hitchhiking another one that does not hardcode the value.
> > 
> > 
> > Done and I should open my own contribution^^ And the plugin reported bans to the Discord. So the question was how the system recognizes it if you don't have to enter the URL of the banlist. And according to the debug message, the plugin should work now because there are no errors in the logs. I use now TheByKotik (sbpp_discord_debug.sp) plugin, she or he added a few changes.
> > [sbpp_discord_debug.zip](https://github.com/sbpp/discord-forward/files/4049748/sbpp_discord_debug.zip)
> 
> Now try send report and ban and mute yourself for a minute.
> In log you must see `SendReport() Ban:` and etc.
> If webhooks are correct but `Missing ban hook endpoints`, it's be very strange.

Hey TheByKotik, unfortunately I did not manage to answer yesterday because I uploaded the plugin during the night and saw the reports only this morning. It works now and thanks for help, I appreciate it :3
![a56c74e8f9f34bed14a54cb365ab3f0e](https://user-images.githubusercontent.com/32603929/72216141-7adf4e00-351d-11ea-9859-1b4a73c95526.png)

**Comment by TheByKotik** [comment]
> > > > `and how does the system recognize the sourcebans of the ban and report them in the discord`
> > > > It uses the forwards. If I understand the question correctly.
> > > > Also, you should really be opening your own issue instead of hitchhiking another one that does not hardcode the value.
> > > 
> > > 
> > > Done and I should open my own contribution^^ And the plugin reported bans to the Discord. So the question was how the system recognizes it if you don't have to enter the URL of the banlist. And according to the debug message, the plugin should work now because there are no errors in the logs. I use now TheByKotik (sbpp_discord_debug.sp) plugin, she or he added a few changes.
> > > [sbpp_discord_debug.zip](https://github.com/sbpp/discord-forward/files/4049748/sbpp_discord_debug.zip)
> > 
> > 
> > Now try send report and ban and mute yourself for a minute.
> > In log you must see `SendReport() Ban:` and etc.
> > If webhooks are correct but `Missing ban hook endpoints`, it's be very strange.
> 
> Hey TheByKotik, unfortunately I did not manage to answer yesterday because I uploaded the plugin during the night and saw the reports only this morning. It works now and thanks for help, I appreciate it :3
> ![a56c74e8f9f34bed14a54cb365ab3f0e](https://user-images.githubusercontent.com/32603929/72216141-7adf4e00-351d-11ea-9859-1b4a73c95526.png)

Sorry, I'm not sure I understood the answer correctly.
Works plugin with debug strings or default plugin?
I simply would not recommend constantly using the debug version.

**Comment by freakexeuLow** [comment]
> 
> 
> > > > > `and how does the system recognize the sourcebans of the ban and report them in the discord`
> > > > > It uses the forwards. If I understand the question correctly.
> > > > > Also, you should really be opening your own issue instead of hitchhiking another one that does not hardcode the value.
> > > > 
> > > > 
> > > > Done and I should open my own contribution^^ And the plugin reported bans to the Discord. So the question was how the system recognizes it if you don't have to enter the URL of the banlist. And according to the debug message, the plugin should work now because there are no errors in the logs. I use now TheByKotik (sbpp_discord_debug.sp) plugin, she or he added a few changes.
> > > > [sbpp_discord_debug.zip](https://github.com/sbpp/discord-forward/files/4049748/sbpp_discord_debug.zip)
> > > 
> > > 
> > > Now try send report and ban and mute yourself for a minute.
> > > In log you must see `SendReport() Ban:` and etc.
> > > If webhooks are correct but `Missing ban hook endpoints`, it's be very strange.
> > 
> > 
> > Hey TheByKotik, unfortunately I did not manage to answer yesterday because I uploaded the plugin during the night and saw the reports only this morning. It works now and thanks for help, I appreciate it :3
> > ![a56c74e8f9f34bed14a54cb365ab3f0e](https://user-images.githubusercontent.com/32603929/72216141-7adf4e00-351d-11ea-9859-1b4a73c95526.png)
> 
> Sorry, I'm not sure I understood the answer correctly.
> Works plugin with debug strings or default plugin?
> I simply would not recommend constantly using the debug version.

I used your plugin with the debug, the standard plugin shows me errors you have seen before in the other thread^^

**Comment by TheByKotik** [comment]
> I used your plugin with the debug, the standard plugin shows me errors you have seen before in the other thread^^

It's very strange.
I just add debug logging and didn't change code.
Can you try download last plugin (.sp) from this repository (not from release tab) and compile it (with your webhook of course)?

**Comment by freakexeuLow** [comment]
> It's very strange.
> I just add debug logging and didn't change code.
> Can you try download last plugin (.sp) from this repository (not from release tab) and compile it (with your webhook of course)?

Mhhhh, it now works i think (he load the plugin normal without any error)
> sm plugins unload sbpp_discord_debug
> [SM] Plugin SourceBans++ Discord Plugin unloaded successfully.
> sm plugins load sbpp_discord
> [SM] Loaded plugin sbpp_discord.smx successfully.

**Comment by TheByKotik** [comment]
> > It's very strange.
> > I just add debug logging and didn't change code.
> > Can you try download last plugin (.sp) from this repository (not from release tab) and compile it (with your webhook of course)?
> 
> Mhhhh, it now works i think (he load the plugin normal without any error)
> 
> > sm plugins unload sbpp_discord_debug
> > [SM] Plugin SourceBans++ Discord Plugin unloaded successfully.
> > sm plugins load sbpp_discord
> > [SM] Loaded plugin sbpp_discord.smx successfully.

Now try send report and ban and mute yourself for a minute for test.

**Comment by freakexeuLow** [comment]
> 
> Now try send report and ban and mute yourself for a minute for test.

it works now, I had also regenerated the webhook before :/
![324d11143e2a8a4e887b14f16343324a](https://user-images.githubusercontent.com/32603929/72218352-7aa17b80-353a-11ea-84ae-579b46e5679d.png)

Thank you for your help and I will close the topic here :3
