### ISSUE TITLE
Crashes with Steamworks 1.2.3b

### ISSUE THREAD

**Issue by LeetDonkey** [sbpp/discord-forward#13]
Crashes the server when Steamworks is updated to 1.2.3b:
https://github.com/KyleSanderson/SteamWorks/releases

I've tried recompiling with the include from 1.2.3b and it doesn't change anything.

**Comment by Bara** [comment]
It would be more helpful when you use [Accelerator](https://forums.alliedmods.net/showthread.php?t=277703) and share your CrashID/URL.

**Comment by LeetDonkey** [comment]
I've been trying to get accelerator to create a crash log, but it doesn't generate anything, and the accelerator.log is 0 bytes.
I need to figure out what's wrong with my accelerator installation before I can provide a crash log

**Comment by LeetDonkey** [comment]
Hello

The crash is here:
https://crash.limetech.org/4mqdh4jdiqi4

Is this enough or do you need more? Like the minidump?

**Comment by TheByKotik** [comment]
I can't reproduce this crash. You run plugin with csgo on linux, right?

**Comment by LeetDonkey** [comment]
Yes, I've tried both Centos 7 and a fresh install of Centos 8.
I tried removing all unnecessary plugins as well.

**Comment by TheByKotik** [comment]
What previous version SteamWorks not crashing?

**Comment by LeetDonkey** [comment]
The last version not crashing on me is this one:
http://users.alliedmods.net/~kyles/builds/SteamWorks/SteamWorks-git132-linux.tar.gz

**Comment by TheByKotik** [comment]
Actually, i think is look like problem with CensOS / System settings / Game server / Beta version SteamWorks extenstion. Can you test please this little plugin. If it crash your server, i think it's not relevant to this plugin. 
```
#include <SteamWorks>

public void OnConfigsExecuted()
{
	int ip[4];
	SteamWorks_GetPublicIP(ip);
}
```

**Comment by rumblefrog** [comment]
Can you include the raw content of the accelerator log on the thread that it crashed, seems to originate from steamclient from an ESP mov to reset to 0.

**Comment by LeetDonkey** [comment]
> Actually, i think is look like problem with CensOS / System settings / Game server / Beta version SteamWorks extenstion. Can you test please this little plugin. If it crash your server, i think it's not relevant to this plugin.
> 
> ```
> #include <SteamWorks>
> 
> public void OnConfigsExecuted()
> {
> 	int ip[4];
> 	SteamWorks_GetPublicIP(ip);
> }
> ```

This crashes the server as well

**Comment by LeetDonkey** [comment]
> Can you include the raw content of the accelerator log on the thread that it crashed, seems to originate from steamclient from an ESP mov to reset to 0.

```
Thread 0 (crashed):
   0: steamclient.so + 0x3817c3
      eip: 0xe4be47c3  esp: 0xffc8edd0  ebp: 0xffc8ee08  ebx: 0x0e143bf0
      esi: 0x0e13d5c0  edi: 0x00006618  eax: 0x098f09b0  ecx: 0xffc8ede0
      edx: 0x5d4b445b  efl: 0x00010246  

      e4be47b4  8d 4d d8           lea ecx, [ebp-0x28]
      e4be47b7  8b 40 04           mov eax, [eax+0x4]
      e4be47ba  8b 10              mov edx, [eax]
      e4be47bc  89 44 24 04        mov [esp+0x4], eax
      e4be47c0  89 0c 24           mov [esp], ecx
  >   e4be47c3  ff 92 94 00 00 00  call dword [edx+0x94]
      e4be47c9  8b 55 e8           mov edx, [ebp-0x18]
      e4be47cc  31 c0              xor eax, eax
      e4be47ce  83 ec 04           sub esp, 0x4
      e4be47d1  85 d2              test edx, edx
      e4be47d3  0f 44 45 d8        cmovz eax, [ebp-0x28]

      ffc8edd0  e0 ed c8 ff b0 09 8f 09  08 ee c8 ff c7 e9 98 ed  ................
      ffc8ede0  f0 3b 14 0e c0 d5 13 0e  08 ee c8 ff 6f f9 52 ec  .;..........o.R.
      ffc8edf0  20 16 b3 0d f8 70 00 00  10 10 6b ed 00 6f 8b 0f   ....p....k..o..
      ffc8ee00  30 68 90 ed 28 ee c8 ff  68 ee c8 ff 9c fa 52 ec  0h..(...h.....R.

      Found via instruction pointer in context
```

Is this what you needed?

**Comment by rumblefrog** [comment]
Ah, you have a different variant of steamclient from mine, perhaps try updating steamclient if not already. But yes, this problem isn't plugin's fault.

**Comment by LeetDonkey** [comment]
> Ah, you have a different variant of steamclient from mine, perhaps try updating steamclient if not already. But yes, this problem isn't plugin's fault.

Yea, the plugin is definately not at fault here, FWIW i tried grabbing the steamclient.so from steamcmd, and it's still crashing, but I'll try to figure something out.

Thanks for helping out
