### ISSUE TITLE
Sending requests not working

### ISSUE THREAD

**Issue by zAfLu** [sbpp/discord-forward#2]
Hello,

we tested the discord webhooks stuff and notice an issue with sending requests.  Everytime a ban is triggered we get the following error message (Message will not be transfered). 

>  L 04/13/2018 - 01:44:23: [SM] Exception reported: Invalid time format or buffer too small
L 04/13/2018 - 01:44:23: [SM] Blaming: sbpp_discord.smx
L 04/13/2018 - 01:44:23: [SM] Call stack trace:
L 04/13/2018 - 01:44:23: [SM]   [0] FormatTime
L 04/13/2018 - 01:44:23: [SM]   [1] Line 92, E:\GameServer\csgoSubSurf\csgo\addons\sourcemod\scripting\sbpp_discord.sp::SendReport
L 04/13/2018 - 01:44:23: [SM]   [2] Line 57, E:\GameServer\csgoSubSurf\csgo\addons\sourcemod\scripting\sbpp_discord.sp::SBPP_OnBanPlayer
L 04/13/2018 - 01:44:23: [SM]   [4] Call_Finish
L 04/13/2018 - 01:44:23: [SM]   [5] Line 2485, .\sbpp_main.sp::CreateBan
L 04/13/2018 - 01:44:23: [SM]   [6] Line 471, .\sbpp_main.sp::CommandBan
L 04/13/2018 - 01:44:24: [SM] Exception reported: Invalid time format or buffer too small
L 04/13/2018 - 01:44:24: [SM] Blaming: sbpp_discord.smx
L 04/13/2018 - 01:44:24: [SM] Call stack trace:
L 04/13/2018 - 01:44:24: [SM]   [0] FormatTime
L 04/13/2018 - 01:44:24: [SM]   [1] Line 92, E:\GameServer\csgoSubSurf\csgo\addons\sourcemod\scripting\sbpp_discord.sp::SendReport
L 04/13/2018 - 01:44:24: [SM]   [2] Line 57, E:\GameServer\csgoSubSurf\csgo\addons\sourcemod\scripting\sbpp_discord.sp::SBPP_OnBanPlayer
L 04/13/2018 - 01:44:24: [SM]   [4] Call_Finish
L 04/13/2018 - 01:44:24: [SM]   [5] Line 2485, .\sbpp_main.sp::CreateBan
L 04/13/2018 - 01:44:24: [SM]   [6] Line 2601, .\sbpp_main.sp::PrepareBan
L 04/13/2018 - 01:44:24: [SM]   [7] Line 809, .\sbpp_main.sp::ReasonSelected

- OS: Windows Server 2012 R2
- SM Version: 1.8.0.6041
- SteamWorks: Git 126
- SMJansson: latest

Already tested:

- [x] Updating Sourcemod
- [x] 1.0.2 & 1.0.3
- [x] Use release binary
- [x] Self compiled version
- [x] SteamWorks  124|121|120 version

We always get the same result. Any ideas?

**Comment by rumblefrog** [comment]
This seems to be a thing on Windows only with Microsoft not supporting the format. To solve this, comment out line 92 and 102 and recompile.

**Comment by rumblefrog** [comment]
Removed in https://github.com/sbpp/discord-forward/commit/b231706d07f43800f8edc61be422d6f7224c5e22 and drafted it for v1.0.4

This decoration data is causing more problem than convenience.

**Comment by zAfLu** [comment]
works fine, thanks m8 :)
