### ISSUE TITLE
[Feature Request] Forward for Mutes / Gags / Blocks

### ISSUE THREAD

**Issue by crashzk** [sbpp/discord-forward#3]
Besides showing the banishes, could put to show the Mutes Gags, and blocks applied in the players.

It would be interesting also to show the players that are unban manually, if any unban admins shows the reason for the unban.

Is it possible to place these updates?

**OBS: Sorry for the lousy English.**

**Comment by rumblefrog** [comment]
References:

- https://github.com/sbpp/sourcebans-pp/blob/v1.x/game/addons/sourcemod/scripting/sbpp_main.sp#L1350 (outdated)

- https://github.com/sbpp/sourcebans-pp/blob/b729ff427d444c7417b98975f0b399d502996c4d/game/addons/sourcemod/scripting/include/sourcecomms.inc#L108

**Comment by crashzk** [comment]
One more thing, bans applied directly by SourceBans are not shown, would it be possible to show also when a player is banned or mutated by the SourceBans Dashboard?

**Comment by rumblefrog** [comment]
Unfortunately, no; not without an immense amount of work to make that happen which by then is not feasible.

**Comment by rumblefrog** [comment]
If you would try out #6 , that'd be great.

**Comment by crashzk** [comment]
I'm trying to compile it just out of error.

http://prntscr.com/l99t1o

**Comment by rumblefrog** [comment]
Include/compiler difference, I've attached it to you on Discord

**Comment by crashzk** [comment]
Apparently it's perfect, it worked properly.

http://prntscr.com/l99umr
