### ISSUE TITLE
Error when you report yourself (for testing)

### ISSUE THREAD

**Issue by tengzl33t** [sbpp/discord-forward#5]
Plugin doesn't work with SteamWorks 130. When i try to send report it write in console: `[sbpp_discord.smx] HTTP request failed for Tengz against Tengz`.

**Comment by rumblefrog** [comment]
Hm, I'll have to try this when I get some time. Meanwhile, could you provide your SM, Metamod, and OS versions?

**Comment by tengzl33t** [comment]
SM 1.10.0.6316, Metamod 1.11.0-dev+1109V and Windows 7 on server.

**Comment by tengzl33t** [comment]
no decision? i tried with SM 1.9 and MM 1.10, doesn't work.

**Comment by rumblefrog** [comment]
Sorry, I'm currently busy with some side projects of my and some exams. I'll have to ask some people to test it for me,

**Comment by tengzl33t** [comment]
it's working well, error when you try to report about yourself only.
