### ISSUE TITLE
Update time from Mute / Gag / Silence to Session when you do not have the time

### ISSUE THREAD

**Issue by crashzk** [sbpp/discord-forward#8]
When we apply a Mute / Gag / Silence by Session the reason that appears in the Discord is `Muted through BaseComm natives` and the time is set to `Permanent`.

http://prntscr.com/mtr1jv
http://prntscr.com/mtr3rl

Would it be possible to leave time as a `Session`?

The reason in the case appears this when the player does not put a reason for the punishment, correct?

**Comment by crashzk** [comment]
I am trying to compile but from the error: http://prntscr.com/mtvd4d

**Comment by rumblefrog** [comment]
https://travis-ci.org/sbpp/discord-forward/jobs/502349237

**Comment by crashzk** [comment]
It's for me does not even compile: http://prntscr.com/mtzuwm

I updated SourceMod the Extension it asks for and nothing....
